
var data = [
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "LE FWD",
        "MSRP": "28850",
        "36 months": "1037.54",
        "48 months": "800.04",
        "60 months": "654.96",
        "City": "8.5",
        "Highway": "6.8",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "LE AWD",
        "MSRP": "30950",
        "36 months": "1108.12",
        "48 months": "854.47",
        "60 months": "699.51",
        "City": "8.7",
        "Highway": "6.9",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "LE AWD Hyrbid",
        "MSRP": "33190",
        "36 months": "1183.41",
        "48 months": "912.52",
        "60 months": "747.03",
        "City": "5.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "XLE AWD ",
        "MSRP": "34550",
        "36 months": "1229.11",
        "48 months": "947.76",
        "60 months": "775.89",
        "City": "8.8",
        "Highway": "7.1",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD ",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "XLE AWD Hybrid",
        "MSRP": "36190",
        "36 months": "1284.23",
        "48 months": "990.27",
        "60 months": "810.68",
        "City": "5.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "SE AWD Hybrid",
        "MSRP": "37990",
        "36 months": "1344.73",
        "48 months": "1036.91",
        "60 months": "848.87",
        "City": "5.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "Trail AWD",
        "MSRP": "38350",
        "36 months": "1356.83",
        "48 months": "1046.24",
        "60 months": "856.51",
        "City": "9.5",
        "Highway": "7.1",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "XSE AWD Hybrid",
        "MSRP": "40650",
        "36 months": "1434.13",
        "48 months": "1105.85",
        "60 months": "905.31",
        "City": "5.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "XSE AWD Hybrid Tech Package",
        "MSRP": "44850",
        "36 months": "1575.29",
        "48 months": "1214.7",
        "60 months": "994.41",
        "City": "5.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "Limited AWD",
        "MSRP": "42850",
        "36 months": "1508.07",
        "48 months": "1162.87",
        "60 months": "951.98",
        "City": "9.5",
        "Highway": "7.1",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "Limited AWD Hybrid",
        "MSRP": "44490",
        "36 months": "1563.19",
        "48 months": "1205.37",
        "60 months": "986.77",
        "City": "5.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Toyota ",
        "Car": "RAV4",
        "Trim": "PRIME SE",
        "MSRP": "44990",
        "36 months": "1431.28",
        "48 months": "1103.65",
        "60 months": "903.51",
        "City": "5.7",
        "Highway": "6.0",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "PHEV",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota",
        "Car": "RAV4",
        "Trim": "PRIME XSE",
        "MSRP": "51590",
        "36 months": "1653.1",
        "48 months": "1274.7",
        "60 months": "1043.53",
        "City": "5.7",
        "Highway": "6.0",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "PHEV",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Toyota ",
        "Car": "RAV4",
        "Trim": "PRIME XSE Tech",
        "MSRP": "56990",
        "36 months": "1834.59",
        "48 months": "1414.64",
        "60 months": "1158.1",
        "City": "5.7",
        "Highway": "6.0",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Compact",
        "Fuel Type": "PHEV",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "LX",
        "MSRP": "24465",
        "36 months": "858.37",
        "48 months": "658.45",
        "60 months": "541.29",
        "City": "7.7",
        "Highway": "6.0",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "EX",
        "MSRP": "26765",
        "36 months": "993.37",
        "48 months": "715.97",
        "60 months": "588.55",
        "City": "7.7",
        "Highway": "6.0",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "Sport",
        "MSRP": "27865",
        "36 months": "969.24",
        "48 months": "743.47",
        "60 months": "611.16",
        "City": "7.8",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "Touring",
        "MSRP": "30265",
        "36 months": "1047.5",
        "48 months": "803.49",
        "60 months": "660.48",
        "City": "7.6",
        "Highway": "6.1",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "Si",
        "MSRP": "33150",
        "36 months": "1150.27",
        "48 months": "884.41",
        "60 months": "732.25",
        "City": "8.7",
        "Highway": "6.4",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "Hatch - LX",
        "MSRP": "28000",
        "36 months": "981.06",
        "48 months": "754.33",
        "60 months": "624.58",
        "City": "8.0",
        "Highway": "6.2",
        "Price/L": "1.4",
        "Category": "Hatchback",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "Hatch - Sport",
        "MSRP": "31500",
        "36 months": "1096.06",
        "48 months": "842.73",
        "60 months": "697.75",
        "City": "7.7",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Hatchback",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Honda",
        "Car": "Civic",
        "Trim": "Hatch - Sport Touring",
        "MSRP": "35000",
        "36 months": "1211.06",
        "48 months": "931.13",
        "60 months": "770.93",
        "City": "7.7",
        "Highway": "6.3",
        "Price/L": "1.4",
        "Category": "Hatchback",
        "Size": "Compact",
        "Fuel Type": "Gasoline",
        "Drivetrain": "FWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Tesla",
        "Car": "Model S",
        "Trim": "Standard",
        "MSRP": "121990",
        "36 months": "3579.0",
        "48 months": "2733.0",
        "60 months": "2225.0",
        "City": "1.7",
        "Highway": "2.2",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Tesla",
        "Car": "Model S",
        "Trim": "Plaid",
        "MSRP": "169990",
        "36 months": "4989.0",
        "48 months": "3809.0",
        "60 months": "3102.0",
        "City": "1.7",
        "Highway": "2.2",
        "Price/L": "1.4",
        "Category": "Sedan",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "Wagon All-Terrain",
        "MSRP": "82900",
        "36 months": "2458.25",
        "48 months": "1882.58",
        "60 months": "1537.6",
        "City": "11.0",
        "Highway": "8.3",
        "Price/L": "1.6",
        "Category": "Wagon",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "No",
        "Lane-keep Assist": "No",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "Wagon All-Terrain + Intelligent Drive Package",
        "MSRP": "89200",
        "36 months": "2645.06",
        "48 months": "2025.65",
        "60 months": "1654.45",
        "City": "11.0",
        "Highway": "8.3",
        "Price/L": "1.6",
        "Category": "Wagon",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "Wagon All-Terrain + Intelligent Drive Package + Comfort Package + Premium Package",
        "MSRP": "93300",
        "36 months": "2766.64",
        "48 months": "2118.76",
        "60 months": "1730.5",
        "City": "11.0",
        "Highway": "8.3",
        "Price/L": "1.6",
        "Category": "Wagon",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "E350 4Matic",
        "MSRP": "66700",
        "36 months": "1977.87",
        "48 months": "1514.69",
        "60 months": "1237.13",
        "City": "11.2",
        "Highway": "8.2",
        "Price/L": "1.6",
        "Category": "Sedan",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "No",
        "Lane-keep Assist": "No",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "E350 4Matic + Intelligent Drive Package",
        "MSRP": "72600",
        "36 months": "2152.82",
        "48 months": "1648.68",
        "60 months": "1346.56",
        "City": "11.2",
        "Highway": "8.2",
        "Price/L": "1.6",
        "Category": "Sedan",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "E350 4Matic + Intelligent Drive Package + Comfort Package + Premium Package",
        "MSRP": "79890",
        "36 months": "2368.99",
        "48 months": "1814.23",
        "60 months": "1481.77",
        "City": "11.2",
        "Highway": "8.2",
        "Price/L": "1.6",
        "Category": "Sedan",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Mercedes-Benz",
        "Car": "E-Class",
        "Trim": "E450 4Matic",
        "MSRP": "76800",
        "36 months": "2277.36",
        "48 months": "1744.06",
        "60 months": "1424.46",
        "City": "10.5",
        "Highway": "7.9",
        "Price/L": "1.6",
        "Category": "Sedan",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "No",
        "Lane-keep Assist": "No",
        "Heated Steering Wheel": "No",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "IONIQ 5",
        "Trim": "Essential",
        "MSRP": "44999",
        "36 months": "1407.88",
        "48 months": "1074.09",
        "60 months": "873.98",
        "City": "1.9",
        "Highway": "2.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "RWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "IONIQ 5",
        "Trim": "Preferred",
        "MSRP": "46999",
        "36 months": "1474.09",
        "48 months": "1124.6",
        "60 months": "915.08",
        "City": "1.9",
        "Highway": "2.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "RWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "IONIQ 5",
        "Trim": "Preferred Long Range",
        "MSRP": "51999",
        "36 months": "1639.62",
        "48 months": "1250.89",
        "60 months": "1017.84",
        "City": "1.9",
        "Highway": "2.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "RWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "IONIQ 5",
        "Trim": "Preferred AWD Long Range",
        "MSRP": "54999",
        "36 months": "1738.94",
        "48 months": "1326.66",
        "60 months": "1079.49",
        "City": "1.9",
        "Highway": "2.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "IONIQ 5",
        "Trim": "Preferred AWD Long Range Premium Package",
        "MSRP": "59999",
        "36 months": "1911.09",
        "48 months": "1458.0",
        "60 months": "1186.36",
        "City": "1.9",
        "Highway": "2.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Electric",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "SANTA FE",
        "Trim": "Essential",
        "MSRP": "33699",
        "36 months": "1181.36",
        "48 months": "899.11",
        "60 months": "729.87",
        "City": "10.6",
        "Highway": "9.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "SANTA FE",
        "Trim": "Preferred",
        "MSRP": "36699",
        "36 months": "1279.93",
        "48 months": "974.13",
        "60 months": "790.76",
        "City": "10.6",
        "Highway": "9.3",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "SANTA FE",
        "Trim": "Urban",
        "MSRP": "40499",
        "36 months": "1398.21",
        "48 months": "1064.16",
        "60 months": "863.84",
        "City": "11.0",
        "Highway": "8.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "SANTA FE",
        "Trim": "Luxury Hybrid",
        "MSRP": "44099",
        "36 months": "1516.5",
        "48 months": "1154.18",
        "60 months": "936.92",
        "City": "7.1",
        "Highway": "7.9",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Hybrid",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "SANTA FE",
        "Trim": "Luxury Hybrid + PHEV",
        "MSRP": "48699",
        "36 months": "1594.94",
        "48 months": "1213.89",
        "60 months": "985.39",
        "City": "3.1",
        "Highway": "3.1",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "PHEV",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "SANTA FE",
        "Trim": "Ultimate Calligraphy",
        "MSRP": "47799",
        "36 months": "1638.07",
        "48 months": "1246.71",
        "60 months": "1012.03",
        "City": "11.0",
        "Highway": "8.5",
        "Price/L": "1.4",
        "Category": "Crossover",
        "Size": "Mid-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "PALISADE",
        "Trim": "Essential",
        "MSRP": "41499",
        "36 months": "1431.07",
        "48 months": "1089.16",
        "60 months": "884.14",
        "City": "12.3",
        "Highway": "9.6",
        "Price/L": "1.4",
        "Category": "SUV",
        "Size": "Full-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "PALISADE",
        "Trim": "Preferred",
        "MSRP": "46499",
        "36 months": "1595.0",
        "48 months": "1214.0",
        "60 months": "986.0",
        "City": "12.3",
        "Highway": "9.6",
        "Price/L": "1.4",
        "Category": "SUV",
        "Size": "Full-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "No"
    },
    {
        "Brand": "Hyundai",
        "Car": "PALISADE",
        "Trim": "Luxury",
        "MSRP": "50699",
        "36 months": "1740.0",
        "48 months": "1324.0",
        "60 months": "1075.0",
        "City": "12.3",
        "Highway": "9.6",
        "Price/L": "1.4",
        "Category": "SUV",
        "Size": "Full-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    },
    {
        "Brand": "Hyundai",
        "Car": "PALISADE",
        "Trim": "Ultimate Calligraphy",
        "MSRP": "54999",
        "36 months": "1875.0",
        "48 months": "1427.0",
        "60 months": "1158.0",
        "City": "12.3",
        "Highway": "9.6",
        "Price/L": "1.4",
        "Category": "SUV",
        "Size": "Full-sized",
        "Fuel Type": "Gasoline",
        "Drivetrain": "AWD",
        "Adaptive Cruise": "Yes",
        "Lane-keep Assist": "Yes",
        "Heated Steering Wheel": "Yes",
        "Cooled Seats": "Yes"
    }
]

const sample = {
    "Brand": "Toyota",
    "Car": "RAV4",
    "Trim": "LE FWD",
    "MSRP": "28850",
    "36 months": "1037.54",
    "48 months": "800.04",
    "60 months": "654.96",
    "City": "8.5",
    "Highway": "6.8",
    "Price/L": "1.4",
    "Category": "Crossover",
    "Size": "Compact",
    "Fuel Type": "Gasoline",
    "Drivetrain": "FWD",
    "Adaptive Cruise": "Yes",
    "Lane-keep Assist": "Yes",
    "Heated Steering Wheel": "No",
    "Cooled Seats": "No"
}

const response = {
    "category": "crossover",
    "payment": "month_36",
    "min_msrp": 10000,
    "max_msrp": 20000,
    "size": "compact",
    "fuel_type": "gasoline",
    "environment": "city",
    "expected_kilometers": 150,
    "trim_options": ["adaptive_cruise", "lane_keep_cruise"],
}

function recommend(data, response) {

    let results = data.filter(datum => datum.Category.toLowerCase() == response.category.toLowerCase())
                      .filter(datum => datum.Size.toLowerCase() == response.size.toLowerCase())
                      .filter(datum => datum["Fuel Type"].toLowerCase() == response.fuel_type.toLowerCase())
                      .filter(function (datum) {
                          let match = false
                          let trim = response.trim_options
                          for (let i=0; i<trim.length; i++) {
                              if (trim[i] == "adaptive_cruise" && datum["Adaptive Cruise"] == "Yes"){ 
                                  continue; 
                                } else if (trim[i] == "lane_keep_cruise" && datum["Lane-keep Assist"] == "Yes") {
                                    continue;
                                } else if (trim[i] == "heated_seated_wheel" && datum["Heated Steering Wheel"] == "Yes") {
                                    continue;
                                } else if (trim[i] == "cooled_seats" && datum["Cooled Seats"] == "Yes") {
                                    continue;
                                } else {
                                    return false
                                }
                          } return true
                      })
                      .filter(datum => response.min_msrp < datum["MSRP"] && response.max_msrp > datum["MSRP"])

    return results
}

function score(filtered_data, response, car)  {
    
    let rank = response.rank
    let cost = 150000
    let score = 0.7*(response.min_msrp / cost) + 0.3 * (1/ rank)

    return score
}

console.log(recommend(data, response))